FROM node:7.3

RUN wget https://github.com/jwilder/dockerize/releases/download/v0.3.0/dockerize-linux-amd64-v0.3.0.tar.gz
RUN tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.3.0.tar.gz

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json
RUN npm install pm2 -g
RUN npm install knex -g
RUN npm install

COPY . /usr/src/app

RUN npm run prestart

WORKDIR /usr/src/app/target